from django.db import models

class KeyTraining(models.Model):

    class Meta:
        db_table = 'key_pairs_trining'

    username= models.CharField( blank=False, null=False,max_length=16)
        
    ft1 = models.DecimalField(max_digits=100,decimal_places=40)
    ft2= models.DecimalField(max_digits=100,decimal_places=40)
    ft3= models.DecimalField(max_digits=100,decimal_places=40)
    ft4= models.DecimalField(max_digits=100,decimal_places=40)
    ft5= models.DecimalField(max_digits=100,decimal_places=40)
    ft6= models.DecimalField(max_digits=100,decimal_places=40)
    ft7= models.DecimalField(max_digits=100,decimal_places=40)
    ft8= models.DecimalField(max_digits=100,decimal_places=40)
    ft9= models.DecimalField(max_digits=100,decimal_places=40)
    ft10= models.DecimalField(max_digits=100,decimal_places=40)
    ft11= models.DecimalField(max_digits=100,decimal_places=40)
    ft12= models.DecimalField(max_digits=100,decimal_places=40)
    ht1= models.DecimalField(max_digits=100,decimal_places=40)
    ht2= models.DecimalField(max_digits=100,decimal_places=40)
    ht3= models.DecimalField(max_digits=100,decimal_places=40)
    ht4= models.DecimalField(max_digits=100,decimal_places=40)
    ht5= models.DecimalField(max_digits=100,decimal_places=40)
    ht6= models.DecimalField(max_digits=100,decimal_places=40)
    ht7= models.DecimalField(max_digits=100,decimal_places=40)
    ht8= models.DecimalField(max_digits=100,decimal_places=40)
    ht9= models.DecimalField(max_digits=100,decimal_places=40)
    ht10= models.DecimalField(max_digits=100,decimal_places=40)
    ht11= models.DecimalField(max_digits=100,decimal_places=40)
    ht12= models.DecimalField(max_digits=100,decimal_places=40)
    ht13= models.DecimalField(max_digits=100,decimal_places=40)
    p_down1= models.DecimalField(max_digits=100,decimal_places=40)
    p_down2= models.DecimalField(max_digits=100,decimal_places=40)
    p_down3= models.DecimalField(max_digits=100,decimal_places=40)
    p_down4= models.DecimalField(max_digits=100,decimal_places=40)
    p_down5= models.DecimalField(max_digits=100,decimal_places=40)
    p_down6= models.DecimalField(max_digits=100,decimal_places=40)
    p_down7= models.DecimalField(max_digits=100,decimal_places=40)
    p_down8= models.DecimalField(max_digits=100,decimal_places=40)
    p_down9= models.DecimalField(max_digits=100,decimal_places=40)
    p_down10= models.DecimalField(max_digits=100,decimal_places=40)
    p_down11= models.DecimalField(max_digits=100,decimal_places=40)
    p_down12= models.DecimalField(max_digits=100,decimal_places=40)
    p_down13= models.DecimalField(max_digits=100,decimal_places=40)
    
    p_up1= models.DecimalField(max_digits=100,decimal_places=40)
    p_up2= models.DecimalField(max_digits=100,decimal_places=40)
    p_up3= models.DecimalField(max_digits=100,decimal_places=40)
    p_up4= models.DecimalField(max_digits=100,decimal_places=40)
    p_up5= models.DecimalField(max_digits=100,decimal_places=40)
    p_up6= models.DecimalField(max_digits=100,decimal_places=40)
    p_up7= models.DecimalField(max_digits=100,decimal_places=40)
    p_up8= models.DecimalField(max_digits=100,decimal_places=40)
    p_up9= models.DecimalField(max_digits=100,decimal_places=40)
    p_up10= models.DecimalField(max_digits=100,decimal_places=40)
    p_up11= models.DecimalField(max_digits=100,decimal_places=40)
    p_up12= models.DecimalField(max_digits=100,decimal_places=40)
    p_up13= models.DecimalField(max_digits=100,decimal_places=40)
    
    s_down1= models.DecimalField(max_digits=100,decimal_places=40)
    s_down2= models.DecimalField(max_digits=100,decimal_places=40)
    s_down3= models.DecimalField(max_digits=100,decimal_places=40)
    s_down4= models.DecimalField(max_digits=100,decimal_places=40)
    s_down5= models.DecimalField(max_digits=100,decimal_places=40)
    s_down6= models.DecimalField(max_digits=100,decimal_places=40)
    s_down7= models.DecimalField(max_digits=100,decimal_places=40)
    s_down8= models.DecimalField(max_digits=100,decimal_places=40)
    s_down9= models.DecimalField(max_digits=100,decimal_places=40)
    s_down10= models.DecimalField(max_digits=100,decimal_places=40)
    s_down11= models.DecimalField(max_digits=100,decimal_places=40)
    s_down12= models.DecimalField(max_digits=100,decimal_places=40)
    s_down13= models.DecimalField(max_digits=100,decimal_places=40)
    s_up1= models.DecimalField(max_digits=100,decimal_places=40)
    s_up2= models.DecimalField(max_digits=100,decimal_places=40)
    s_up3= models.DecimalField(max_digits=100,decimal_places=40)
    s_up4= models.DecimalField(max_digits=100,decimal_places=40)
    s_up5= models.DecimalField(max_digits=100,decimal_places=40)
    s_up6= models.DecimalField(max_digits=100,decimal_places=40)
    s_up7= models.DecimalField(max_digits=100,decimal_places=40)
    s_up8= models.DecimalField(max_digits=100,decimal_places=40)
    s_up9= models.DecimalField(max_digits=100,decimal_places=40)
    s_up10= models.DecimalField(max_digits=100,decimal_places=40)
    s_up11= models.DecimalField(max_digits=100,decimal_places=40)
    s_up12= models.DecimalField(max_digits=100,decimal_places=40)
    s_up13= models.DecimalField(max_digits=100,decimal_places=40)
    
    c_x_down1= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down2= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down3= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down4= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down5= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down6= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down7= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down8= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down9= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down10= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down11= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down12= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_down13= models.DecimalField(max_digits=100,decimal_places=40)
    
    c_x_up1= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up2= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up3= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up4= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up5= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up6= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up7= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up8= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up9= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up10=models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up11= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up12= models.DecimalField(max_digits=100,decimal_places=40)
    c_x_up13= models.DecimalField(max_digits=100,decimal_places=40)
    
    c_y_down1= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down2= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down3= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down4= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down5=models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down6= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down7= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down8= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down9=models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down10= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down11= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down12= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_down13= models.DecimalField(max_digits=100,decimal_places=40)
    
    c_y_up1= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up2= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up3= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up4= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up5= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up6= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up7= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up8= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up9= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up10= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up11= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up12= models.DecimalField(max_digits=100,decimal_places=40)
    c_y_up13= models.DecimalField(max_digits=100,decimal_places=40)
    
    acc_mean_x= models.DecimalField(max_digits=100,decimal_places=40)
    acc_mean_y= models.DecimalField(max_digits=100,decimal_places=40)
    acc_mean_z= models.DecimalField(max_digits=100,decimal_places=40)
    acc_s_x= models.DecimalField(max_digits=100,decimal_places=40)
    acc_s_y= models.DecimalField(max_digits=100,decimal_places=40)
    acc_s_z=models.DecimalField(max_digits=100,decimal_places=40)
    acc_sd_x= models.DecimalField(max_digits=100,decimal_places=40)
    acc_sd_y= models.DecimalField(max_digits=100,decimal_places=40)
    acc_sd_z= models.DecimalField(max_digits=100,decimal_places=40)
    
    gyr_mean_x= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_mean_y= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_mean_z= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_s_x= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_s_y= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_s_z= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_sd_x= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_sd_y= models.DecimalField(max_digits=100,decimal_places=40)
    gyr_sd_z= models.DecimalField(max_digits=100,decimal_places=40)

    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_edited = models.DateTimeField(auto_now=True, null=True)
   
    def __str__(self):
        return self.username